<!DOCTYPE html>
<html lang="en"><head>
<script src="test_2_082025_files/libs/clipboard/clipboard.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tabby.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/popper.min.js"></script>
<script src="test_2_082025_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="test_2_082025_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="test_2_082025_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content=" Lesley Chapman Hannah, Ph.D., M.S. College of Graduate Studies Northeast Ohio Medical University">
  <title>Describing Continuous Data: Center, Spread, Shape, and Interval Probability</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="test_2_082025_files/libs/revealjs/dist/theme/quarto-2c1b5f745a11cfad616ebade4a4a7d24.css">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="test_2_082025_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h2 style="color: #2A76DD;" class="title">Describing Continuous Data: Center, Spread, Shape, and Interval Probability</h2>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div style="font-size:20px;" class="quarto-title-author-name">
<br><br><span style="font-size:25px;"><strong>Lesley Chapman Hannah, Ph.D., M.S.</strong></span><br>College of Graduate Studies<br>Northeast Ohio Medical University 
</div>
</div>
</div>

</section>
<section class="slide level2">

<h3 id="workflow-for-describing-continuous-data">Workflow for Describing Continuous Data</h3>
<div style="font-size:0.68em">
<ul>
<li><p>describing continuous data before modeling involves a simialr sequence of steps as described for discrete values:</p>
<ol type="1">
<li>define the observational unit<br>
</li>
<li>identify the variable as continuous<br>
</li>
<li>determine summaries of center and spread<br>
</li>
<li>evaluate distribution shape across the measurement scale<br>
</li>
<li>select visualizations that preserve numerical structure and distribution form</li>
</ol></li>
<li><p>numerical summaries and graphical displays with how quantitative values are recorded and help describe what the measurements represent across patients</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="workflow-and-descriptive-interpretation">Workflow and Descriptive Interpretation</h3>
<div style="font-size:0.68em">
<p>Each step in the workflow defines a component of continuous measurements described by statistical summaries or plots:</p>
<ul>
<li><code>observational unit</code>: determines what one recorded value represents within the study design<br>
</li>
<li><code>continuous variable</code>: defines the measurement as a quantitative value on a numerical scale<br>
</li>
<li><code>summary</code>: quantifies central tendency and dispersion<br>
</li>
<li><code>distribution analysis</code>: evaluates symmetry, skewness, tails, and concentration across the scale<br>
</li>
<li><code>probability representation</code>: expresses how much of the sample falls within domain-specific ranges<br>
</li>
<li><code>visualization</code>: encodes the distribution in a form that preserves scale, shape, and comparability</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="define-the-observational-unit">Define the Observational Unit</h3>
<div style="font-size:0.67em">
<p>Review:</p>
<ul>
<li>observational unit is the entity represented by one row of data</li>
<li>each observational unit contributes one numerical value measured on a quantitative scale</li>
</ul>
<p>Continuous examples of observational units include:</p>
<ul>
<li>one patient encounter<br>
</li>
<li>one blood draw<br>
</li>
<li>one biopsy specimen<br>
</li>
<li>one laboratory assay result<br>
</li>
<li>one follow-up visit</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="identify-continuous-variables">Identify Continuous Variables</h3>
<div style="font-size:0.67em">
<p>After the observational unit is established, continuous variables are recognized by how values are recorded:</p>
<ul>
<li>values are quantitative rather than labels<br>
</li>
<li>values can vary across a numerical scale<br>
</li>
<li>values may take many distinct magnitudes within an interval<br>
</li>
</ul>
<p>Examples in biomedical data include:</p>
<ul>
<li>cytokine concentration<br>
</li>
<li>blood pressure<br>
</li>
<li>serum creatinine<br>
</li>
<li>tumor size</li>
</ul>
<p>Descriptive summaries for continuous data help determine:</p>
<ul>
<li>where values are centered<br>
</li>
<li>how widely values vary<br>
</li>
<li>how values are distributed across the scale</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="determine-the-data-summary-for-continuous-variables">Determine the Data Summary for Continuous Variables</h3>
<div style="font-size:0.67em">
<ul>
<li><p>continuous variables are commonly described with summaries of center, spread, and shape :</p>
<ul>
<li><code>mean</code> : arithmetic center of the sample<br>
</li>
<li><code>median</code> : middle ordered value<br>
</li>
<li><code>standard deviation</code> : variability around the sample mean<br>
</li>
<li><code>interquartile range</code> : spread of the middle 50% of observations<br>
</li>
<li><code>minimum and maximum</code> : observed range endpoints<br>
</li>
<li><code>quantiles</code> : positional summaries along the ordered scale</li>
</ul></li>
<li><p>no single summary fully describes a continuous distribution</p></li>
<li><p>valid description combines numerical summaries with plots that show how values occupy the measurement scale</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="continuous-distributions-describe-measurement-structure">Continuous Distributions Describe Measurement Structure</h3>
<div style="font-size:0.67em">
<ul>
<li><p>continuous distributions describe how measured values are organized across the numerical scale</p></li>
<li><p>descriptive statistical analysis involves summarizing how values are distributed across observational units without removing the scale on which the measurements were recorded</p></li>
</ul>
<p>For continuous variables, descriptive summaries show:</p>
<ul>
<li><p><strong>center</strong> → where values tend to cluster along the scale</p></li>
<li><p><strong>spread</strong> → how widely values vary around the center</p></li>
<li><p><strong>shape</strong> → whether the distribution is symmetric, skewed, heavy-tailed, or multi-peaked</p></li>
<li><p><strong>range and tails</strong> → whether observations extend into unusually low or high values</p></li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="probability-quantifies-where-continuous-values-fall">Probability Quantifies Where Continuous Values Fall</h3>
<div style="font-size:0.67em">
<p>For continuous data, descriptive probability is often expressed over an interval of values rather than at one exact value</p>
<p>For a sample of size <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[
\hat{P}(a \le X \le b) = \frac{\text{number of observations with values between } a \text{ and } b}{n}
\]</span></p>
<p>Formula defines the probability that a measured value falls within the interval from <span class="math inline">\(a\)</span> to <span class="math inline">\(b\)</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(X\)</span> : continuous variable<br>
</li>
<li><span class="math inline">\(a\)</span> : lower bound of the interval<br>
</li>
<li><span class="math inline">\(b\)</span> : upper bound of the interval<br>
</li>
<li><span class="math inline">\(n\)</span> : total number of observations</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="visualizations-for-continuous-data">Visualizations for Continuous Data</h3>
<div style="font-size:0.67em">
<ul>
<li>plots are chosen to preserve the numerical scale and reveal how values occupy that scale</li>
</ul>
<p>Visualizations for continuous variables include:</p>
<ul>
<li><code>histogram</code> : shows how observations accumulate across intervals of the scale<br>
</li>
<li><code>density plot</code> : shows a smooth estimate of distribution shape<br>
</li>
<li><code>boxplot</code> : summarizes median, quartiles, and tail extension<br>
</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="data-overview-continuous-biomarkers-in-respiratory-infection">Data Overview: Continuous Biomarkers in Respiratory Infection</h3>
<div style="font-size:0.67em">
<p><strong>Background</strong>: Suppose we observe inflammatory biomarkers collected from a cohort of patients evaluated for respiratory infection</p>
<p>Each row represents one patient visit, and each variable records a continuous biological measurement:</p>
<ul>
<li><code>il6</code> : interleukin-6 concentration in [pg/mL]<br>
</li>
<li><code>tnf_alpha</code> : tumor necrosis factor-alpha concentration in [pg/mL]<br>
</li>
<li><code>neutrophils</code> : neutrophil count in units of [<span class="math inline">\(10^9\)</span>/L]</li>
</ul>
<p>Research Question:</p>
<blockquote>
<p>How are these biomarker values distributed across patients, and what do center, spread, and shape indicate about the observed sample?</p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="simulated-biomarker-dataset">Simulated Biomarker Dataset</h3>
<div style="font-size:0.64em">
<ul>
<li>dataset of 220 patient-level observations, where each row corresponds to a single clinical visit and each column represents a continuous biomarker measurement</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">303</span>)</span>
<span id="cb1-2"><a href=""></a></span>
<span id="cb1-3"><a href=""></a>biomarker_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-4"><a href=""></a>  <span class="at">patient_id =</span> <span class="fu">sprintf</span>(<span class="st">"B%03d"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">220</span>),</span>
<span id="cb1-5"><a href=""></a>  <span class="at">il6 =</span> <span class="fu">round</span>(<span class="fu">rlnorm</span>(<span class="dv">220</span>, <span class="at">meanlog =</span> <span class="fu">log</span>(<span class="dv">12</span>), <span class="at">sdlog =</span> <span class="fl">0.70</span>), <span class="dv">2</span>),</span>
<span id="cb1-6"><a href=""></a>  <span class="at">tnf_alpha =</span> <span class="fu">round</span>(<span class="fu">rlnorm</span>(<span class="dv">220</span>, <span class="at">meanlog =</span> <span class="fu">log</span>(<span class="dv">18</span>), <span class="at">sdlog =</span> <span class="fl">0.45</span>), <span class="dv">2</span>),</span>
<span id="cb1-7"><a href=""></a>  <span class="at">neutrophils =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">220</span>, <span class="at">mean =</span> <span class="fl">5.9</span>, <span class="at">sd =</span> <span class="fl">1.3</span>), <span class="dv">2</span>)</span>
<span id="cb1-8"><a href=""></a>)</span>
<span id="cb1-9"><a href=""></a></span>
<span id="cb1-10"><a href=""></a>biomarker_df <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  patient_id   il6 tnf_alpha neutrophils
  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
1 B001        8.47      27.4        6.17
2 B002       14.6       15.1        4.6 
3 B003       15.7       16.1        4.85
4 B004       12.6       12.0        5.11
5 B005        8.01      19.9        8.88
6 B006       30.1       22.5        5.99
7 B007        4.96      22.8        5.72
8 B008        7.21      13.3        4.42</code></pre>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="mean-and-median-two-summaries-of-center">Mean and Median: Two Summaries of Center</h3>
<div style="font-size:0.67em">
<p><strong>Mean</strong> is expressed as:</p>
<p><span class="math display">\[
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i
\]</span></p>
<p>Average of all observed values in the sample</p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> : sample mean<br>
</li>
<li><span class="math inline">\(n\)</span> : number of observations<br>
</li>
<li><span class="math inline">\(x_i\)</span> : observed value for the <span class="math inline">\(i\)</span>th observational unit<br>
</li>
<li><span class="math inline">\(\sum_{i=1}^{n} x_i\)</span> : total of all observed values</li>
</ul>
<p><strong>Median</strong> : middle value after the sample is ordered from smallest to largest</p>
<ul>
<li>mean uses the magnitude of every value<br>
</li>
<li>median uses the order of values in the sample</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="standard-deviation-and-interquartile-range">Standard Deviation and Interquartile Range</h3>
<div style="font-size:0.67em">
<p><strong>Standard deviation</strong>:</p>
<ul>
<li>measure that captures variability around the mean</li>
<li>summary of dispersion that quantifies how far observations extend from the mean across the entire distribution</li>
</ul>
<p><span class="math display">\[
s = \sqrt{ \frac{1}{n - 1} \sum (x_i - \bar{x})^2 }
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(s\)</span> : sample standard deviation<br>
</li>
<li><span class="math inline">\(x_i\)</span> : observed value for the <span class="math inline">\(i\)</span>th observation<br>
</li>
<li><span class="math inline">\(\bar{x}\)</span> : sample mean<br>
</li>
<li><span class="math inline">\((x_i-\bar{x})^2\)</span> : squared deviation from the mean<br>
</li>
<li><span class="math inline">\(n-1\)</span> : denominator used for the sample-based estimate of variability</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="standard-deviation-and-interquartile-range-1">Standard Deviation and Interquartile Range</h3>
<div style="font-size:0.67em">
<p><strong>Interquartile Range</strong>:</p>
<ul>
<li>width of the central interval containing the middle 50% of ordered observations</li>
<li>measure of dispersion</li>
<li>summary statistic for skewed variables and data with outliers</li>
</ul>
<p><span class="math display">\[
IQR = Q_3 - Q_1
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(Q_1\)</span> : 25th percentile [value below which 25% of observations fall]</li>
<li><span class="math inline">\(Q_3\)</span> : 75th percentile [value below which 75% of observations fall]</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="numerical-summary-for-il-6">Numerical Summary for IL-6</h3>
<div style="font-size:0.7em">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  mean_il6 median_il6 sd_il6 iqr_il6 q1_il6 q3_il6 min_il6 max_il6
     &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     14.7       11.7   10.6    12.3   7.26   19.5    1.77    71.7</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li><p><code>mean_il6</code> [14.7]: average of IL-6 concentrations across all patients</p></li>
<li><p><code>median_il6</code> [11.7]: 50th percentile of the ordered IL-6 values</p>
<ul>
<li>point at which half of observations fall below and half above</li>
</ul></li>
<li><p><code>sd_il6</code> [10.6]: quantifies the overall dispersion of IL-6 values around the mean</p>
<ul>
<li>variability across the full distribution</li>
</ul></li>
<li><p><code>iqr_il6</code> [12.3]: range spanned by the central 50% of IL-6 values</p>
<ul>
<li>measure of variability that reflects the spread of the majority of observations</li>
</ul></li>
<li><p><code>q1_il6</code> [7.26] and <code>q3_il6</code> [19.5]: 50% of IL-6 values fall between 7.26 and 19.5 pg/mL</p>
<ul>
<li>interval captures the central concentration range of the sample</li>
</ul></li>
<li><p><code>min_il6</code> [1.77] and <code>max_il6</code> [71.7]: lower and upper bounds of IL-6 in the sample</p></li>
</ul>
<p>Example: focus on evaluating IL-6</p>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-distribution-histogram">IL-6 Distribution: Histogram</h3>
<div style="font-size:0.67em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-4-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>right-skewed histogram shows how a continuous biomarker (IL-6 concentration) is distributed across patients</li>
<li>tallest bars indicate the IL-6 concentration range where most patients are observed</li>
<li>bars at high values represent patients with elevated inflammatory response</li>
<li>horizontal spread of the bars shows that IL-6 values range widely</li>
<li>long tail extending to the right indicates right-skewness <span class="math inline">\(\rightarrow\)</span> small number of patients have substantially higher IL-6 levels</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-distribution-density-plot">IL-6 Distribution : Density Plot</h3>
<div style="font-size:0.64em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>density plot : smooth representation of how IL-6 values are distributed across patient observations</li>
<li>distribution is right-skewed, with most values concentrated around 10–15 pg/mL [region representing the most common range of observed values]</li>
<li>curve is right-skewed gradually declines as IL-6 increases, showing that higher concentrations occur less frequently</li>
<li>values span a wide range, extending from low concentrations to substantially elevated values [above ~50 pg/mL]</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-distribution">IL-6 Distribution</h3>
<div style="font-size:0.64em">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>bars show how IL-6 observations accumulate across intervals of the measurement scale</li>
<li>density curve traces the smooth distributional shape implied by those observations</li>
<li>agreement between the bars and the curve confirms the main concentration of the sample</li>
</ul>
<p>Note:</p>
<ul>
<li><code>histogram</code> displays how many observations fall within intervals</li>
<li><code>density plot</code> estimates how probability is distributed across a continuous scale</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-boxplot">IL-6: Boxplot</h3>
<div style="font-size:0.64em">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">ggplot</span>(biomarker_df, <span class="fu">aes</span>(<span class="at">y =</span> il6)) <span class="sc">+</span></span>
<span id="cb4-2"><a href=""></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href=""></a>  <span class="fu">labs</span>(</span>
<span id="cb4-4"><a href=""></a>    <span class="at">title =</span> <span class="st">"Boxplot of IL-6 Concentration"</span>,</span>
<span id="cb4-5"><a href=""></a>    <span class="at">y =</span> <span class="st">"IL-6 (pg/mL)"</span>,</span>
<span id="cb4-6"><a href=""></a>    <span class="at">x =</span> <span class="cn">NULL</span></span>
<span id="cb4-7"><a href=""></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="test_2_082025_files/figure-revealjs/unnamed-chunk-7-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>boxplot summarizes the distribution of IL-6 concentrations across patient observations using quartiles and the median</li>
<li>line inside the box marks the median</li>
<li>lower and upper box boundaries mark 𝑄1 and 𝑄3</li>
<li>height of the box corresponds to the interquartile range</li>
<li>points beyond the whiskers indicate outliers</li>
<li>median IL-6 concentration is approximately 11.7 pg/mL, indicating the central location of the distribution</li>
<li>interquartile range (IQR ≈ 12.3 pg/mL) : moderate spread among the central observations</li>
<li>middle 50% of values lies between <span class="math inline">\(Q_1 \approx 7.26\)</span> pg/mL and <span class="math inline">\(Q_3 \approx 19.5\)</span> pg/mL, defining the primary concentration range</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-histogram-to-probability">IL-6: Histogram to Probability</h3>
<div style="font-size:0.67em">
<ul>
<li>continuous biomarker such as IL-6 can be treated as a random variable:</li>
</ul>
<p><span class="math display">\[X=\text{IL-6 concentration [pg/mL]}\]</span></p>
<p>probability helps answer:</p>
<ul>
<li>how likely are different IL-6 values?</li>
<li>where is probability concentrated?</li>
<li>how does probability change across the measurement scale?</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-histogram-to-probability-1">IL-6: Histogram to Probability</h3>
<div style="font-size:0.67em">
<ul>
<li><p>histogram approximates how probability is distributed across intervals of IL-6</p>
<ul>
<li>bar height reflects relative frequency, which approximates probability</li>
<li>dividing counts by total sample size converts counts into approximate probabilities</li>
</ul></li>
</ul>
<p><strong>Interpretation</strong></p>
<ul>
<li>regions with taller bars correspond to higher probability density</li>
<li>low bars in the right tail indicate low-probability</li>
<li>total area across all bars corresponds to probability ≈ 1</li>
</ul>
<p><span class="math display">\[\text{∑relative frequencies≈1}\]</span></p>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-density-as-a-probability-model">IL-6: Density as a Probability Model</h3>
<div style="font-size:0.67em">
<ul>
<li>density curve represents an estimate of the probability density function [PDF] of IL-6</li>
</ul>
<p><span class="math display">\[\text{f(x)=density at IL-6 value x}\]</span></p>
<p>Key properties:</p>
<ul>
<li><span class="math inline">\(f(x)≥0\)</span></li>
<li>total area under the curve equals 1</li>
</ul>
<p><span class="math display">\[
\int_{-\infty}^{\infty} f(x)\,dx = 1
\]</span> Interpretation:</p>
<ul>
<li>height of the curve reflects relative likelihood of IL-6 values near x</li>
<li>area under the curve over an interval gives probability</li>
</ul>
<p>Example:</p>
<p><span class="math display">\[
P(10 \le X \le 20) = \int_{10}^{20} f(x)\,dx
\]</span> - value corresponds to the region where most IL-6 values are concentrated or the probability that X falls in the 10 to 20 interval</p>
</div>
</section>
<section class="slide level2">

<h3 id="il-6-boxplot-and-probability">IL-6: Boxplot and Probability</h3>
<div style="font-size:0.67em">
<ul>
<li>boxplot summarizes probability using quantiles</li>
</ul>
<p>Quantiles partition probability:</p>
<ul>
<li><span class="math inline">\(Q_1\)</span> : 25th percentile → 25% of observations fall below this value</li>
<li>median: 50th percentile</li>
<li><span class="math inline">\(Q_3\)</span> : 75th percentile</li>
</ul>
<p><span class="math display">\[
P(X \le Q_1) = 0.25, \quad P(X \le \text{Median}) = 0.5
\]</span></p>
<p>Interpretation for IL-6:</p>
<ul>
<li>middle 50% of probability lies between:</li>
</ul>
<p><span class="math display">\[7.26≤X≤19.5\]</span> - interval defines the highest-density region of the distribution</p>
<p>Outliers:</p>
<ul>
<li>represent observations in low-probability regions</li>
<li>often correspond to clinically extreme cases</li>
</ul>
</div>
</section>
<section class="slide level2">

<h3 id="summary">Summary</h3>
<div style="font-size:0.67em">
<p>descriptive features define how the sample should be understood before later modeling decisions are made</p>
<p>plots and probabilities describing continuous variables help answer:</p>
<ul>
<li><code>mean and median</code>: describe where the sample is centered<br>
</li>
<li><code>standard deviation and IQR</code>: describe how widely values vary<br>
</li>
<li><code>histograms and density plots</code>: describe shape and concentration across the scale<br>
</li>
<li><code>boxplots</code>: describe ordered spread and tail extension<br>
</li>
<li><code>interval probabilities</code>: describe the fraction of values occupying clinically meaningful ranges</li>
</ul>
<p>metrics help determine whether values are:</p>
<ul>
<li>approximately symmetric<br>
</li>
<li>right-skewed or left-skewed<br>
</li>
<li>tightly concentrated or broadly dispersed<br>
</li>
<li>characterized by extended tails or unusually large values</li>
</ul>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="test_2_082025_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="test_2_082025_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="test_2_082025_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1400,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>